# Main workflow file
# File: .github/workflows/terraform.yml
name: 'Terraform Pipeline'
 
on:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Terraform Setup
      uses: ./.github/actions/terraform-setup
      with:          
          gcp_credentials: ${{ secrets.GCP_CREDS }}
 
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
 
    
